-- Módulo Referentes - Frente Cultura
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.referentes (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  period text not null default '',
  name text not null,
  phone text not null default '',
  discipline text not null default '',
  source text not null default '',
  original_status text not null default '',
  original_notes text not null default '',
  raw_data jsonb not null default '{}'::jsonb,
  contacted boolean not null default false,
  contact_date date,
  response text not null default '',
  information_provided text not null default '',
  follow_up text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists referentes_workspace_idx on public.referentes(workspace_id);
create index if not exists referentes_workspace_name_idx on public.referentes(workspace_id, name);

alter table public.referentes enable row level security;

revoke all on table public.referentes from anon, authenticated;
grant select, insert, update, delete on table public.referentes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'referentes' and policyname = 'workspace members view referentes'
  ) then
    create policy "workspace members view referentes" on public.referentes
    for select to authenticated using (private.is_workspace_member(workspace_id));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'referentes' and policyname = 'workspace editors add referentes'
  ) then
    create policy "workspace editors add referentes" on public.referentes
    for insert to authenticated with check (private.can_edit_workspace(workspace_id));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'referentes' and policyname = 'workspace editors update referentes'
  ) then
    create policy "workspace editors update referentes" on public.referentes
    for update to authenticated using (private.can_edit_workspace(workspace_id)) with check (private.can_edit_workspace(workspace_id));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'referentes' and policyname = 'workspace editors delete referentes'
  ) then
    create policy "workspace editors delete referentes" on public.referentes
    for delete to authenticated using (private.can_edit_workspace(workspace_id));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'referentes'
  ) then
    alter publication supabase_realtime add table public.referentes;
  end if;
end $$;
