-- Frente Cultura: esquema inicial seguro para Supabase
create schema if not exists private;

create table public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'editor' check (role in ('admin', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create table public.members (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null,
  base integer,
  role text not null default 'Sin designar',
  created_at timestamptz not null default now()
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  phase smallint not null check (phase between 1 and 3),
  title text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.activities (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null,
  activity_date date not null,
  place text not null default '',
  attendees integer not null default 0 check (attendees >= 0),
  adherents integer not null default 0 check (adherents >= 0),
  status text not null default 'Planificada' check (status in ('Planificada', 'En curso', 'Realizada')),
  created_at timestamptz not null default now()
);

create table public.contacts (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null,
  type text not null check (type in ('Artista', 'Espacio cultural', 'Organización cultural', 'Agrupación', 'Colectividad', 'Peña')),
  discipline text not null default '',
  neighborhood text not null default '',
  address text not null default '',
  phone text not null default '',
  latitude double precision,
  longitude double precision,
  sustained boolean not null default false,
  created_at timestamptz not null default now()
);

create index members_workspace_idx on public.members(workspace_id);
create index tasks_workspace_phase_idx on public.tasks(workspace_id, phase);
create index activities_workspace_date_idx on public.activities(workspace_id, activity_date);
create index contacts_workspace_idx on public.contacts(workspace_id);
create index workspace_members_user_idx on public.workspace_members(user_id);

create or replace function private.is_workspace_member(target_workspace uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members wm
    where wm.workspace_id = target_workspace
      and wm.user_id = (select auth.uid())
  );
$$;

create or replace function private.can_edit_workspace(target_workspace uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members wm
    where wm.workspace_id = target_workspace
      and wm.user_id = (select auth.uid())
      and wm.role in ('admin', 'editor')
  );
$$;

revoke all on function private.is_workspace_member(uuid) from public, anon;
revoke all on function private.can_edit_workspace(uuid) from public, anon;
grant execute on function private.is_workspace_member(uuid) to authenticated;
grant execute on function private.can_edit_workspace(uuid) to authenticated;

alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.members enable row level security;
alter table public.tasks enable row level security;
alter table public.activities enable row level security;
alter table public.contacts enable row level security;

revoke all on table public.workspaces, public.workspace_members, public.members, public.tasks, public.activities, public.contacts from anon, authenticated;
grant select on table public.workspaces, public.workspace_members to authenticated;
grant select, insert, update, delete on table public.members, public.tasks, public.activities, public.contacts to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "members can view workspace" on public.workspaces
for select to authenticated using (private.is_workspace_member(id));

create policy "members can view memberships" on public.workspace_members
for select to authenticated using (private.is_workspace_member(workspace_id));

create policy "workspace members view team" on public.members
for select to authenticated using (private.is_workspace_member(workspace_id));
create policy "workspace editors add team" on public.members
for insert to authenticated with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors update team" on public.members
for update to authenticated using (private.can_edit_workspace(workspace_id)) with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors delete team" on public.members
for delete to authenticated using (private.can_edit_workspace(workspace_id));

create policy "workspace members view tasks" on public.tasks
for select to authenticated using (private.is_workspace_member(workspace_id));
create policy "workspace editors add tasks" on public.tasks
for insert to authenticated with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors update tasks" on public.tasks
for update to authenticated using (private.can_edit_workspace(workspace_id)) with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors delete tasks" on public.tasks
for delete to authenticated using (private.can_edit_workspace(workspace_id));

create policy "workspace members view activities" on public.activities
for select to authenticated using (private.is_workspace_member(workspace_id));
create policy "workspace editors add activities" on public.activities
for insert to authenticated with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors update activities" on public.activities
for update to authenticated using (private.can_edit_workspace(workspace_id)) with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors delete activities" on public.activities
for delete to authenticated using (private.can_edit_workspace(workspace_id));

create policy "workspace members view contacts" on public.contacts
for select to authenticated using (private.is_workspace_member(workspace_id));
create policy "workspace editors add contacts" on public.contacts
for insert to authenticated with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors update contacts" on public.contacts
for update to authenticated using (private.can_edit_workspace(workspace_id)) with check (private.can_edit_workspace(workspace_id));
create policy "workspace editors delete contacts" on public.contacts
for delete to authenticated using (private.can_edit_workspace(workspace_id));

insert into public.workspaces (id, name)
values ('00000000-0000-4000-8000-000000000001', 'Frente Cultura');

insert into public.members (workspace_id, name, base) values
('00000000-0000-4000-8000-000000000001','Nati Garibotto',2),
('00000000-0000-4000-8000-000000000001','Fer Fiscella',4),
('00000000-0000-4000-8000-000000000001','Dana Vergara',2),
('00000000-0000-4000-8000-000000000001','Pablo Maccarini',2),
('00000000-0000-4000-8000-000000000001','Sofía Arévalo',null),
('00000000-0000-4000-8000-000000000001','Hernán Quiroga',2),
('00000000-0000-4000-8000-000000000001','Cele Irigoyemborde',2),
('00000000-0000-4000-8000-000000000001','Nicolás Martínez',3),
('00000000-0000-4000-8000-000000000001','César Valicenti',2),
('00000000-0000-4000-8000-000000000001','Nicolás Bruno',2),
('00000000-0000-4000-8000-000000000001','Mati Venzi',null),
('00000000-0000-4000-8000-000000000001','Carolina Melitón',2),
('00000000-0000-4000-8000-000000000001','Leo Lora',2),
('00000000-0000-4000-8000-000000000001','Lucía Palacios',null),
('00000000-0000-4000-8000-000000000001','Lucre Caresia',null),
('00000000-0000-4000-8000-000000000001','Agustín Alfonso',null);

insert into public.tasks (workspace_id, phase, title) values
('00000000-0000-4000-8000-000000000001',1,'Mapeo de artistas, espacios culturales, agrupaciones y colectividades'),
('00000000-0000-4000-8000-000000000001',1,'Peña militante del 17 de Octubre'),
('00000000-0000-4000-8000-000000000001',1,'Agenda compartida con el área de Cultura municipal'),
('00000000-0000-4000-8000-000000000001',2,'Ciclo de cultura en los barrios: peñas, murales y música'),
('00000000-0000-4000-8000-000000000001',2,'Propuestas de verano al aire libre'),
('00000000-0000-4000-8000-000000000001',2,'Talleres barriales abiertos'),
('00000000-0000-4000-8000-000000000001',3,'Festival popular en fecha patria o peronista'),
('00000000-0000-4000-8000-000000000001',3,'Encuentro de espacios culturales'),
('00000000-0000-4000-8000-000000000001',3,'Registro de hacedores culturales del partido');

insert into public.activities (workspace_id, name, activity_date, place)
values ('00000000-0000-4000-8000-000000000001','Peña militante del 17 de Octubre','2026-10-17','A definir');

alter publication supabase_realtime add table public.members, public.tasks, public.activities, public.contacts;

-- Después de crear un usuario en Authentication > Users,
-- vinculalo al espacio ejecutando este ejemplo con su correo:
-- insert into public.workspace_members (workspace_id, user_id, role)
-- select '00000000-0000-4000-8000-000000000001', id, 'admin'
-- from auth.users where email = 'tu-correo@ejemplo.com';
